language: python
python:
  - 2.7
install:
  - npm i -g npm
  - npm install
  - pip install -r requirements.dev.txt
  - pip install coveralls
script:
  - coverage run manage.py test
  - flake8 .
after_success:
  - coveralls
notifications:
  slack:
    secure: D2UrTxFolji0qnKvRMqnearuRqdsu9IAdLzOd3d/jOIVtzc2Nqmzd70s2sWLx4rtX/vKbeqEpz1yf738GR48hZhKIy07ySB/hi7u2TelafPzAmaZ+k0jUzWsfACVKpkF77IjSgQ29orUDNUuac2Hc8Wo+niYS3cqVwRprZKmkrs=
